print("hi")
print("hello")
print("prints down")
print("hi ",end="")
print("hello",end="")
print("ends with space")
print("hi ",end=",")
print("hello",end=",")
print("ends with comma")
print("hi ",end=":")
print("hello",end=",")
print("ends with colon")
print("hi ",end="\t")
print("hello",end="\t")
print("ends with tab space")

