fp1=open("one.txt","r")
data=fp1.read()
fp2=open("two.txt","w")
fp2.write(data)
fp3=open("three.txt","a")
fp3.write(data)
print("new file created")
fp4=open("three.txt","x")
fp4.write(data)
fp1.close()
fp2.close()
fp3.close()
fp4.close()
